# Generated by Django 5.2.14 on 2026-05-13 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialCompany',
            fields=[
                ('fin_co_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('homp_url', models.URLField(blank=True, null=True)),
                ('cal_tel', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('fin_prdt_cd', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=20)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('join_way', models.TextField(blank=True, null=True)),
                ('join_member', models.TextField(blank=True, null=True)),
                ('join_deny', models.IntegerField(default=1)),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('max_limit', models.BigIntegerField(blank=True, null=True)),
                ('dcls_month', models.CharField(max_length=6)),
                ('dcls_strt_day', models.CharField(max_length=8)),
                ('dcls_end_day', models.CharField(blank=True, max_length=8, null=True)),
                ('rsrv_type', models.CharField(blank=True, max_length=10, null=True)),
                ('prft_strc', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.financialcompany')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(max_length=5)),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField(blank=True, null=True)),
                ('intr_rate2', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
